---
title: "Samarth Patel"
author: Samarth Patel
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
         
    # set it to true for a self-contained HTML page but it'll take longer to render
    
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================
Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> drsamarthpatel@gmail.com
- <i class="fa fa-github"></i> [github.com/datascalpel](https://github.com/datascalpel)
- <i class="fa fa-phone"></i> +91 8828548257
- <i class="fa fa-twitter"></i> [twitter.com/data_scalpel](https://twitter.com/data_scalpel)
- <i class="fa fa-linkedin"></i> https://www.linkedin.com/in/samarth
- DOB November 4th, 1992
- 3001, Type III Building, Seven Hills Hospital, Andheri East, Mumbai, India 400059


Nonsurgical Skills {#skills}
--------------------------------------------------------------------------------

+ Experienced in statistical analysis with Microsoft Excel, SPSS, and R.
+ Data wrangling with tidyverse, Data Visualization with ggplot2
+ Reproducible Research With R markdown.This CV is written by me in R markdown.
+ Regression analysis in R 

Language Fluency
--------------------------------------------------------------------------------

- English **Advanced**
- Gujarati **Native/Functionally Native**
- Hindi **Native/Functionally Native**
- Marathi **Basic**
- Sanskrit **Intermediate**

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

**Samarth Patel M.B.B.S. , M.S. General SUrgery** {#title}
--------------------------------------------------------------------------------

### Actively seeking for a clinical/translational research position

General Surgery Post graduate (**PGY 5**) from Mumbai, India |Avid Data science learner and R programmer | ECFMG Certified | USMLE Step 1 Score 253 | USMLE step 2CK Score 253 | ***NRMP Match General Surgery/CT Surgery Residency*** in the USA | Cricket and Table Tennis | Hiking, Cycling Enthusiastic


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### B.J. Medical College and Gujarat University

Bachelor of Medicine & Bachelor of Surgery (M.B.B.S)

Ahmedabad, India

2010-2016

Here is the [link to my Graduate Valedictorian speech](https://www.youtube.com/watch?v=JVjqGJvdVJ8) 

### Seth G.S.Medical College and KEM Hospital, MUHS

M.S. in General Surgery

Mumbai, India

2016-2019

Thesis: Factors Predicting Outcomes in Necrotizing Soft Tissue Infections(NSTIs)

### USMLE Step 1 

Scored 253 (First Attempt)

Mumbai, India

Sept 2020

### USMLE step 2CK 

Scored 253 (First Attempt)

Ahmedabad, India

March 2021

### Occupational English Test (OET) Medicine 

400/450/400/380 (First Attempt)

Mumbai, India

April 2021


Surgical  Experience {data-icon=user-md}
--------------------------------------------------------------------------------

### Full time Assistant Professor cum Lecturer in General Surgery 

King Edward Memorial Hospital

Mumbai, India

01/08/2019 - 12/10/2020

- Performed a large number of elective and emergency surgeries on a broad range of medical conditions such as GI tract ( perforations, Ischemic Bowel Disease, Liver resections, Splenectomy, Gastrectomy,Colon and Rectum, Perineal Procedures),Breast & Endocrine( Mastectomy, Thyroidectomy, Parathyroidectomy, Pancreatic enucleations,Adrenalectomies),Head and Neck (MRND, Parotidectomy, Hemimandibulectomy, Glossectomy), PVD (minor and Major Amputations, Fasciotomy,Limb revascularization),Laparoscopic Appendectomy, Lap Cholecystectomy, TEP, TAPP hernia Reapairs.
- Mastered the  Principles and Practice of Surgical Energy.

### Junior Consultant in General Surgery

Seven Hills Hospital.

Mumbai, India

Present - 02/03/2021

- I was consulatnt in-charge of the 20 Bedded Covid ICU at the largest Covid Facility in India (2000 Beds), trained fellow consultants by performing substantial numbers of bedside procedures (Tube thoracostomy, tracheostomy,Suprapubic catheter insertion, Central venous catheterization,Hemodialysis port insertion) and Mechanical Ventilator operations for ARDS
  

Honors and Awards {data-icon=award}
--------------------------------------------------------------------------------

### Second Position , *Surgical-Quiz*

The Association of Surgeons of India.

Mumbai, India

Dec 2018

### National Rank 59 out of >96,000 Students

All India Post Graduation Medical Entrace Examination (AIPGME).

New Delhi, India

January 2016

### Indian Oil Corporation Limited (IOCL) Scholarship

B.J.Medical College, MBBS Batch 2010

Ahmedabad, India

2010-2014

Workshops and Seminars {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Proctology live operative workshop and CME

The Association of Surgeons of India (ASI)

Mumbai, India

March 218

### Inguinal Hernia live Operative Workshop and CME

Mumbai Surgical Society and ASI

Mumbai, India

August 2018

### Clinical Research Methods workshop

Department of Pharmacology, Seth G.S.Medical College.

Mumbai, India

July 2018

### Multidisciplinary Solution to rare and not so rare Breast and Thyroid Issues, live operative workshop 

International College Of Surgeons, Indian Chapter (West Zone)

Mumbai, India

October 2018

Selected Publications {data-icon=file}
--------------------------------------------------------------------------------

### Factors Predicting Outcomes In Necrotizing Soft Tissue Infections(NSTIs).

Thesis Submitted to Maharashtra University of Health sciences (MUHS)

Mumbai, India

March 2019

**Samarth Patel**, Shilpa A Rao.

### Hyperphosphatemic Tumoral Calcinosis : A rare Clinico-Pathological Disorder.

Indian Journal Of Surgery

[Hyperphosphatemic Tumoral Calcinosis : A rare Clinico-Pathological Disorder](https://doi.org/10.1007/s12262-018-1855-8)

Jan 2019

Rege S, Singh Amiteshwar,**Patel S**, Vairagar S

### Retrosternal Goiter:When do we need a sternotomy?

A case series (In submission) 

N/A

Aug 2021

Garale M, Dalvi A, **Patel S**,Mathai G, Desai A.